---
version: '3.4'
volumes:
  db_test:
  solr_test:
services:
  db:
    image: postgres:10-alpine
    read_only: true
    volumes:
    - type: volume
      source: db_test
      target: /data
    - type: volume
      target: /tmp
    - type: volume
      target: /var/log
    - type: volume
      target: /var/run
    environment:
    - PGDATA=/data
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=d0ck3r
    ports:
    - 5434:5432
    healthcheck:
      test: "CMD echo 'SELECT 1' | PGPASSWORD=d0ck3r psql --host 127.0.0.1 --username docker
  --dbname docker --quiet --no-align --tuples-only"
      interval: 30s
      timeout: 5s
      retries: 3
  solr:
    image: solr:7.2-alpine
    read_only: true
    volumes:
    - type: volume
      source: solr_test
      target: /opt/solr/server/solr
    - type: volume
      target: /opt/solr/server
    - type: volume
      target: /tmp
    - type: volume
      target: /var/log
    - type: volume
      target: /var/run
    - type: bind
      source: $PWD/solr
      target: /opt/solr/server/solr/configsets/_default
    ports:
    - 8985:8983
    command: solr-precreate blacklight-core
    healthcheck:
      test:
      - CMD
      - wget
      - "-O"
      - "/dev/null"
      - http://localhost:8983/solr/
      interval: 30s
      timeout: 5s
      retries: 3
