---
version: '3.4'
volumes:
  db:
  solr:
  html:
services:
  web:
    image: geoblacklight/gblstack_web
    depends_on:
      - lsyncd
    ports:
      - "3000:3000"
    links:
      - "solr"
    environment:
      - RAILS_ENV=development
      - SOLR_URL="http://solr:8983/solr/blacklight-core"
    volumes:
      - html:/usr/src/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
  db:
    image: postgres:10-alpine
    read_only: true
    volumes:
    - type: volume
      source: db
      target: /data
    - type: volume
      target: /tmp
    - type: volume
      target: /var/log
    - type: volume
      target: /var/run
    environment:
    - PGDATA=/data
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=d0ck3r
    ports:
    - 5433:5432
    healthcheck:
      test: "CMD echo 'SELECT 1' | PGPASSWORD=d0ck3r psql --host 127.0.0.1 --username docker
  --dbname docker --quiet --no-align --tuples-only"
      interval: 30s
      timeout: 5s
      retries: 3
  solr:
    image: solr:8.3-slim
    read_only: true
    volumes:
    - type: volume
      source: solr
      target: /opt/solr/server/solr
    - type: volume
      target: /opt/solr/server
    - type: volume
      target: /tmp
    - type: volume
      target: /var/log
    - type: volume
      target: /var/run
    - type: bind
      source: $PWD/solr
      target: /opt/solr/server/solr/configsets/_default
    ports:
    - 8983:8983
    command: solr-precreate blacklight-core
    healthcheck:
      test:
      - CMD
      - wget
      - "-O"
      - "/dev/null"
      - http://localhost:8983/solr/
      interval: 30s
      timeout: 5s
      retries: 3
  lsyncd:
    image: allthings/lsyncd
    command: -rsync /mnt/html /var/www/html
    volumes:
      - $PWD/.:/mnt/html
      - html:/var/www/html
